<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import AppLayout from '../components/layout/AppLayout.vue'; import DatePicker from '../components/ui/DatePicker.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import { createEarning, deleteEarning, listEarnings, updateEarning } from '../services/earnings'; import { apiErrorMessage } from '../services/api'; import { formatDate, formatMoney } from '../utils/formatters'; import type { Earning, EarningPayload } from '../types';
const rows = ref<Earning[]>([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const editing = ref<number | null>(null); const filters = reactive({ search: '', source: '', date_from: '', date_to: '' }); const form = reactive<EarningPayload>({ earning_date: '', source: '', description: '', amount: 0, reference: null, note: null });
async function load(): Promise<void> { loading.value = true; try { rows.value = (await listEarnings(filters)).data; error.value = ''; } catch (e) { error.value = apiErrorMessage(e); } finally { loading.value = false; } }
function reset(): void { editing.value = null; Object.assign(form, { earning_date: '', source: '', description: '', amount: 0, reference: null, note: null }); }
function edit(row: Earning): void { editing.value = row.id; Object.assign(form, { earning_date: row.earning_date, source: row.source, description: row.description, amount: Number(row.amount), reference: row.reference, note: row.note }); }
async function save(): Promise<void> { saving.value = true; try { if (editing.value) await updateEarning(editing.value, form); else await createEarning(form); reset(); await load(); } catch (e) { error.value = apiErrorMessage(e); } finally { saving.value = false; } }
async function remove(id: number): Promise<void> { if (confirm('Delete this earning?')) { await deleteEarning(id); await load(); } }
onMounted(load);
</script>
<template><AppLayout><div><p class="text-sm font-medium text-brand-700">Finance</p><h1 class="mt-1 text-3xl font-semibold">Earnings</h1><p class="mt-1 text-sm text-slate-500">Admin-only company revenue records.</p></div><form class="card mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" @submit.prevent="load"><label><span class="label">Search</span><input v-model="filters.search" class="field" /></label><label><span class="label">Source</span><input v-model="filters.source" class="field" /></label><label><span class="label">From</span><DatePicker v-model="filters.date_from" /></label><label><span class="label">To</span><DatePicker v-model="filters.date_to" /></label><BaseButton type="submit">Filter</BaseButton></form><section class="card mt-6"><h2 class="font-semibold">{{ editing ? 'Edit earning' : 'Add earning' }}</h2><form class="mt-4 grid gap-3 sm:grid-cols-2" @submit.prevent="save"><label><span class="label">Date</span><DatePicker v-model="form.earning_date" /></label><label><span class="label">Source / Category</span><input v-model="form.source" class="field" placeholder="Client Payment" /></label><label><span class="label">Description</span><input v-model="form.description" class="field" /></label><label><span class="label">Amount</span><input v-model.number="form.amount" class="field" type="number" min="0.01" step="0.01" /></label><label><span class="label">Reference / Note</span><input v-model="form.reference" class="field" /></label><label class="sm:col-span-2"><span class="label">Details</span><textarea v-model="form.note" class="field" rows="2" /></label><div class="flex gap-2 sm:col-span-2"><BaseButton type="submit" :disabled="saving">{{ editing ? 'Update' : 'Add earning' }}</BaseButton><BaseButton v-if="editing" type="button" variant="secondary" @click="reset">Cancel</BaseButton></div></form></section><p v-if="error" class="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{{ error }}</p><LoadingState v-if="loading" label="Loading earnings…" /><section v-else class="mt-6 overflow-hidden rounded-xl border bg-white"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Date</th><th class="p-3">Source</th><th class="p-3">Description</th><th class="p-3 text-right">Amount</th><th class="p-3">Actions</th></tr></thead><tbody class="divide-y"><tr v-for="row in rows" :key="row.id"><td class="p-3">{{ formatDate(row.earning_date) }}</td><td class="p-3">{{ row.source }}</td><td class="p-3">{{ row.description }}</td><td class="p-3 text-right font-semibold">{{ formatMoney(row.amount) }}</td><td class="p-3"><button class="mr-3 text-brand-700" @click="edit(row)">Edit</button><button class="text-red-700" @click="remove(row.id)">Delete</button></td></tr></tbody></table></div><p v-if="!rows.length" class="p-8 text-center text-sm text-slate-500">No earnings found.</p></section></AppLayout></template>
