<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import AppLayout from '../components/layout/AppLayout.vue'; import BaseButton from '../components/ui/BaseButton.vue'; import BaseDialog from '../components/ui/BaseDialog.vue'; import LoadingState from '../components/ui/LoadingState.vue'; import { listUsers, createUser, updateUser } from '../services/users'; import { apiErrorMessage, validationErrors } from '../services/api'; import type { User, ValidationErrors } from '../types';
const users = ref<User[]>([]); const selected = ref<User | null>(null); const open = ref(false); const loading = ref(true); const saving = ref(false); const error = ref(''); const errors = ref<ValidationErrors>({}); const form = reactive({ name: '', email: '', password: '', role: 'staff', is_active: true });
async function load(): Promise<void> { loading.value = true; try { users.value = await listUsers(); } catch(e) { error.value = apiErrorMessage(e); } finally { loading.value = false; } }
function edit(user?: User): void { selected.value = user ?? null; Object.assign(form, user ? { name: user.name, email: user.email, password: '', role: user.role, is_active: user.is_active } : { name: '', email: '', password: '', role: 'staff', is_active: true }); errors.value = {}; open.value = true; }
async function save(): Promise<void> { saving.value = true; errors.value = {}; const payload: Record<string, unknown> = { name: form.name, email: form.email, role: form.role, is_active: form.is_active }; if (form.password) payload.password = form.password; try { if (selected.value) await updateUser(selected.value.id, payload); else await createUser({ ...payload, password: form.password }); open.value = false; await load(); } catch(e) { error.value = apiErrorMessage(e); errors.value = validationErrors(e); } finally { saving.value = false; } }
onMounted(load);
</script>
<template><AppLayout><div class="flex items-end justify-between"><div><p class="text-sm font-medium text-brand-700">Administration</p><h1 class="mt-1 text-3xl font-semibold">Users</h1><p class="mt-1 text-sm text-slate-500">Manage access, roles, and account status.</p></div><BaseButton @click="edit()">Add user</BaseButton></div><p v-if="error" class="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{{ error }}</p><LoadingState v-if="loading" label="Loading users…" /><section v-else class="mt-6 overflow-hidden rounded-xl border bg-white"><div class="divide-y"><button v-for="user in users" :key="user.id" class="flex w-full items-center justify-between p-5 text-left hover:bg-slate-50" @click="edit(user)"><div><strong>{{ user.name }}</strong><p class="text-sm text-slate-500">{{ user.email }}</p></div><div class="text-right"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{{ user.role }}</span><p class="mt-1 text-xs" :class="user.is_active ? 'text-emerald-700' : 'text-red-700'">{{ user.is_active ? 'Active' : 'Inactive' }}</p></div></button></div></section><BaseDialog v-model:open="open" :title="selected ? 'Edit user' : 'New user'" description="Set the user's account details and role."><form class="mt-5 space-y-4" @submit.prevent="save"><label class="block"><span class="label">Name</span><input v-model="form.name" class="field" /><span v-if="errors.name" class="error-text">{{ errors.name[0] }}</span></label><label class="block"><span class="label">Email</span><input v-model="form.email" class="field" type="email" /><span v-if="errors.email" class="error-text">{{ errors.email[0] }}</span></label><label class="block"><span class="label">{{ selected ? 'New password (optional)' : 'Password' }}</span><input v-model="form.password" class="field" type="password" minlength="12" /><span v-if="errors.password" class="error-text">{{ errors.password[0] }}</span></label><label class="block"><span class="label">Role</span><select v-model="form.role" class="field"><option value="staff">Staff</option><option value="admin">Administrator</option></select></label><label class="flex items-center gap-2 text-sm"><input v-model="form.is_active" type="checkbox" />Active account</label><div class="flex justify-end gap-2"><BaseButton variant="secondary" @click="open = false">Cancel</BaseButton><BaseButton type="submit" :loading="saving">Save user</BaseButton></div></form></BaseDialog></AppLayout></template>
